# Generated by Django 4.0.4 on 2022-05-14 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='belt',
            field=models.ForeignKey(db_column='Пояс', on_delete=django.db.models.deletion.CASCADE, to='diplom.belt', verbose_name='Пояс'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='client',
            field=models.ForeignKey(db_column='Клиент', on_delete=django.db.models.deletion.CASCADE, to='diplom.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='competition',
            field=models.ForeignKey(db_column='Соревнование', on_delete=django.db.models.deletion.CASCADE, to='diplom.competition', verbose_name='Соревнование'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='date_assignment',
            field=models.DateField(db_column='Дата присвоения', verbose_name='Дата присвоения'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='passport_number',
            field=models.CharField(db_column='Номер паспорта спортсмена', max_length=20, verbose_name='Номер паспорта спортсмена'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='rank',
            field=models.ForeignKey(db_column='Разряд', on_delete=django.db.models.deletion.CASCADE, to='diplom.rank', verbose_name='Разряд'),
        ),
        migrations.AlterField(
            model_name='belt',
            name='name',
            field=models.CharField(db_column='Пояс', max_length=20, verbose_name='Пояс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_birth',
            field=models.DateField(db_column='Дата рождения', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_enrollment',
            field=models.DateField(db_column='Дата зачисления', verbose_name='Дата зачисления'),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstname',
            field=models.CharField(db_column='Имя', max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='growth',
            field=models.CharField(db_column='Рост', max_length=10, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(db_column='Отчество', max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(db_column='Номер телефона', max_length=20, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(db_column='Фамилия', max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.CharField(db_column='Вес', max_length=10, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='date_birth',
            field=models.DateField(db_column='Дата рождения', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='date_enrollment',
            field=models.DateField(db_column='Дата зачисления', verbose_name='Дата зачисления'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='firstname',
            field=models.CharField(db_column='Имя', max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='patronymic',
            field=models.CharField(db_column='Отчество', max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone_number',
            field=models.CharField(db_column='Номер телефона', max_length=30, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='surname',
            field=models.CharField(db_column='Фамилия', max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='coaching',
            name='entry_id',
            field=models.ForeignKey(db_column='Запись', on_delete=django.db.models.deletion.CASCADE, to='diplom.entry', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='coaching',
            name='practice_id',
            field=models.ForeignKey(db_column='Тренировка', on_delete=django.db.models.deletion.CASCADE, to='diplom.practice', verbose_name='Тренировка'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='certification_competition',
            field=models.BooleanField(db_column='Аттестация', verbose_name='Аттестация'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='coach_id',
            field=models.ForeignKey(db_column='Тренер', on_delete=django.db.models.deletion.CASCADE, to='diplom.coach', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='cost',
            field=models.CharField(db_column='Стоимость', max_length=20, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateField(db_column='Дата', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='place',
            field=models.CharField(db_column='Место проведения', max_length=50, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='rating_id',
            field=models.ForeignKey(db_column='Рейтинг', on_delete=django.db.models.deletion.CASCADE, to='diplom.rating', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='speaker_id',
            field=models.ForeignKey(db_column='Выступающий', on_delete=django.db.models.deletion.CASCADE, to='diplom.speaker', verbose_name='Выступающий'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='time',
            field=models.TimeField(db_column='Время', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(db_column='Наименование', max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='group',
            field=models.ForeignKey(db_column='Группа', on_delete=django.db.models.deletion.CASCADE, to='diplom.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='statement',
            field=models.ForeignKey(db_column='Заявление', on_delete=django.db.models.deletion.CASCADE, to='diplom.statement', verbose_name='Заявление'),
        ),
        migrations.AlterField(
            model_name='group',
            name='data_formation',
            field=models.DateField(db_column='Дата формирования', verbose_name='Дата формирования'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(db_column='Описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(db_column='Название зала', max_length=50, verbose_name='Название зала'),
        ),
        migrations.AlterField(
            model_name='packagedocuments',
            name='document',
            field=models.ForeignKey(db_column='Пакет документов', on_delete=django.db.models.deletion.CASCADE, to='diplom.document', verbose_name='Пакет документов'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='coach',
            field=models.ForeignKey(db_column='Тренер', on_delete=django.db.models.deletion.CASCADE, to='diplom.coach', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='cost',
            field=models.CharField(db_column='Стоимость', max_length=20, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date',
            field=models.DateField(db_column='Дата', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='hall',
            field=models.ForeignKey(db_column='Зал', on_delete=django.db.models.deletion.CASCADE, to='diplom.hall', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='time',
            field=models.TimeField(db_column='Время', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(db_column='Разряд', max_length=50, verbose_name='Разряд'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.CharField(db_column='Рейтинг', max_length=50, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='competition_id',
            field=models.ForeignKey(db_column='Мероприятие', on_delete=django.db.models.deletion.CASCADE, to='diplom.competition', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='entry',
            field=models.ForeignKey(db_column='Запись', on_delete=django.db.models.deletion.CASCADE, to='diplom.entry', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='client',
            field=models.ForeignKey(db_column='Клиент', on_delete=django.db.models.deletion.CASCADE, to='diplom.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='contract_number',
            field=models.CharField(db_column='Номер договора', max_length=20, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='data_start_contract',
            field=models.DateField(db_column='Дата начала договора', verbose_name='Дата начала договора'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='data_statement',
            field=models.DateField(db_column='Дата заявления', verbose_name='Дата заявления'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='data_stop_contract',
            field=models.DateField(db_column='Дата окончания договора', verbose_name='Дата окончания договора'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='package_documents',
            field=models.ForeignKey(db_column='Пакет документов', on_delete=django.db.models.deletion.CASCADE, to='diplom.packagedocuments', verbose_name='Пакет документов'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='passport_number',
            field=models.CharField(db_column='Номер паспорта', max_length=20, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='passport_series',
            field=models.CharField(db_column='Серия паспорта', max_length=20, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='payment_status',
            field=models.BooleanField(db_column='Статус оплаты', default=False, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='type_statement',
            field=models.ForeignKey(db_column='Тип заявления', on_delete=django.db.models.deletion.CASCADE, to='diplom.typestatement', verbose_name='Тип заявления'),
        ),
        migrations.AlterField(
            model_name='typestatement',
            name='name',
            field=models.CharField(db_column='Тип заявления', max_length=30, verbose_name='Тип заявления'),
        ),
    ]
