# Generated by Django 4.0.4 on 2022-05-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0002_alter_competition_certification_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='certification_competition',
            field=models.CharField(choices=[('COMP', 'Соревнование'), ('CERF', 'Аттестация')], db_column='Аттестация_соревнования', max_length=20, verbose_name='Аттестация_соревнования'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='coach_id',
            field=models.ForeignKey(db_column='id_тренера(FK)', on_delete=django.db.models.deletion.CASCADE, to='diplom.coach', verbose_name='id_тренера(FK)'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='rating_id',
            field=models.ForeignKey(db_column='id_рейтинга(FK)', on_delete=django.db.models.deletion.CASCADE, to='diplom.rating', verbose_name='id_рейтинга(FK)'),
        ),
    ]
