# Generated by Django 4.0.4 on 2022-05-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0003_remove_competition_speaker_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedocuments',
            name='document',
        ),
        migrations.AddField(
            model_name='packagedocuments',
            name='document',
            field=models.ManyToManyField(db_column='Пакет документов', to='diplom.document', verbose_name='Пакет документов'),
        ),
    ]
