# Generated by Django 4.0.4 on 2022-05-26 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0003_alter_competition_certification_competition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='client',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='competition',
        ),
        migrations.AddField(
            model_name='achievements',
            name='speaker',
            field=models.ForeignKey(db_column='id_выступающего(FK)', default='', on_delete=django.db.models.deletion.CASCADE, to='diplom.speaker', verbose_name='id_выступающего(FK)'),
        ),
    ]
